x <- c(1,9,2,8,3,9,4,5,7,6)
mean(x)
median(x)
var(x)
sd(x)
summary(x)
x <- rnorm(1000)
hist(x)
dotchart(x)
boxplot(x)
x
median(x)
#plot()
hist(airquality$Wind, xlab = "Wind")
boxplot(airquality$Wind, xlab = "Wind", ylab = "Speed")
boxplot(Wind~Month, airquality, xlab = "Month", ylab = "Speed")

plot(airquality$Wind,airquality$Temp, xlab = "Wind",ylab = "Temp")

with(airquality,plot(Wind,Temp,type = "n"))
title("The relationship between temp and wind")
with(subset(airquality,Month==5),points(Wind,Temp,col="red"))
with(subset(airquality,Month==6),points(Wind,Temp,col="blue"))
with(subset(airquality,Month==7),points(Wind,Temp,col="green"))
with(subset(airquality,Month==8),points(Wind,Temp,col="black"))
fit <- lm(Temp~Wind, airquality)
abline(fit, lwd = 2,col = "yellow")
legend("topright", pch = 1,col = c("red","blue","green","black"),legend = c(5,6,7,8))
#par()
par("bg")
par("col")
par("mar")
par("mfrow")
par("mfcol")
?par

par(mfrow = c(1,2))
hist(airquality$Wind)
hist(airquality$Temp)

par(mfrow = c(1,1))
boxplot(airquality$Wind)

#lattice
library(lattice)
xyplot(Temp~Ozone, data = airquality)
airquality$Month <- factor(airquality$Month)
xyplot(Temp~Ozone|Month, data = airquality, layout = c(5,1))
